name: 'Okay'
dependencies:
  test:
environment:
  sdk: '>=2.10.0 <3.0.0'
  browser: '>=0.10.0 <0.11.0'
  dart_to_js_script_rewriter: '^1.0.1'
transformers:
dev_dependencies:
  # ···
  build_runner: ^2.1.0
  build_test: ^2.1.0
  build_web_compilers: ^3.0.0
